[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = "0.11.12"
noto-sans-mono-bitmap = { version = "0.3.1", features = ["size_24"] }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name="kernel"
test = false
bench = false